### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by iamsj7** [ShivamKumarJha/Dummy_DT#1]
Hello bro !
Update the realme rmx1851 to latest packages A15.
Directly you have emerged android Q beta update.

**Comment by iamsj7** [comment]
I have extracted and pushed the a15 update here 
https://GitHub.com/iamsj7/_dump

**Comment by ShivamKumarJha** [comment]
> I have extracted and pushed the a15 update here
> https://GitHub.com/iamsj7/_dump

https://github.com/ShivamKumarJha/Dummy_DT/commit/b62ebf659f1fcde2244dc1070e3c62eda450d955

**Comment by iamsj7** [comment]
Pro thanks

**Comment by iamsj7** [comment]
Bro can you please share the bash scripts for this

**Comment by ShivamKumarJha** [comment]
> Bro can you please share the bash scripts for this

contains my github & telegram bot token, so gotta clean first

**Comment by iamsj7** [comment]
Will be waiting for it
